name: WARP-ULTRA
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
          curl -O https://raw.githubusercontent.com/ALIILAPRO/warp-plus-go/main/warp-plus.py
          python3 warp-plus.py <<EOF
          ${{ secrets.WARP_ID }}
          EOF
