name: WARP-GET
on:
  workflow_dispatch: # 手动运行开关
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Script
        run: |
          wget https://github.com/ALIILAPRO/warp-plus-go/releases/download/v1.0.8/warp-plus-go_1.0.8_linux_amd64.tar.gz
          tar -xvf warp-plus-go_1.0.8_linux_amd64.tar.gz
          chmod +x ./warp-plus-go
          ./warp-plus-go --id ${{ secrets.WARP_ID }} --make
